package com.wangkuo.zxb.coreservice.db.po;

public class SbCustomerVipGoodInterval {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good_interval.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good_interval.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good_interval.good_type
     *
     * @mbggenerated
     */
    private Integer goodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good_interval.begin_sec
     *
     * @mbggenerated
     */
    private Float beginSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good_interval.end_sec
     *
     * @mbggenerated
     */
    private Float endSec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good_interval.id
     *
     * @return the value of sb_customer_vip_good_interval.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good_interval.id
     *
     * @param id the value for sb_customer_vip_good_interval.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good_interval.customer_id
     *
     * @return the value of sb_customer_vip_good_interval.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good_interval.customer_id
     *
     * @param customerId the value for sb_customer_vip_good_interval.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good_interval.good_type
     *
     * @return the value of sb_customer_vip_good_interval.good_type
     *
     * @mbggenerated
     */
    public Integer getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good_interval.good_type
     *
     * @param goodType the value for sb_customer_vip_good_interval.good_type
     *
     * @mbggenerated
     */
    public void setGoodType(Integer goodType) {
        this.goodType = goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good_interval.begin_sec
     *
     * @return the value of sb_customer_vip_good_interval.begin_sec
     *
     * @mbggenerated
     */
    public Float getBeginSec() {
        return beginSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good_interval.begin_sec
     *
     * @param beginSec the value for sb_customer_vip_good_interval.begin_sec
     *
     * @mbggenerated
     */
    public void setBeginSec(Float beginSec) {
        this.beginSec = beginSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good_interval.end_sec
     *
     * @return the value of sb_customer_vip_good_interval.end_sec
     *
     * @mbggenerated
     */
    public Float getEndSec() {
        return endSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good_interval.end_sec
     *
     * @param endSec the value for sb_customer_vip_good_interval.end_sec
     *
     * @mbggenerated
     */
    public void setEndSec(Float endSec) {
        this.endSec = endSec;
    }
}