package com.wangkuo.zxb.coreservice.db.po;

import java.math.BigDecimal;

public class SbCustomerVipRoutePrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route_price.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route_price.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route_price.vip_route_id
     *
     * @mbggenerated
     */
    private Long vipRouteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route_price.good_type
     *
     * @mbggenerated
     */
    private Integer goodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route_price.begin_sec
     *
     * @mbggenerated
     */
    private Float beginSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route_price.end_sec
     *
     * @mbggenerated
     */
    private Float endSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route_price.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route_price.id
     *
     * @return the value of sb_customer_vip_route_price.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route_price.id
     *
     * @param id the value for sb_customer_vip_route_price.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route_price.customer_id
     *
     * @return the value of sb_customer_vip_route_price.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route_price.customer_id
     *
     * @param customerId the value for sb_customer_vip_route_price.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route_price.vip_route_id
     *
     * @return the value of sb_customer_vip_route_price.vip_route_id
     *
     * @mbggenerated
     */
    public Long getVipRouteId() {
        return vipRouteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route_price.vip_route_id
     *
     * @param vipRouteId the value for sb_customer_vip_route_price.vip_route_id
     *
     * @mbggenerated
     */
    public void setVipRouteId(Long vipRouteId) {
        this.vipRouteId = vipRouteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route_price.good_type
     *
     * @return the value of sb_customer_vip_route_price.good_type
     *
     * @mbggenerated
     */
    public Integer getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route_price.good_type
     *
     * @param goodType the value for sb_customer_vip_route_price.good_type
     *
     * @mbggenerated
     */
    public void setGoodType(Integer goodType) {
        this.goodType = goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route_price.begin_sec
     *
     * @return the value of sb_customer_vip_route_price.begin_sec
     *
     * @mbggenerated
     */
    public Float getBeginSec() {
        return beginSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route_price.begin_sec
     *
     * @param beginSec the value for sb_customer_vip_route_price.begin_sec
     *
     * @mbggenerated
     */
    public void setBeginSec(Float beginSec) {
        this.beginSec = beginSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route_price.end_sec
     *
     * @return the value of sb_customer_vip_route_price.end_sec
     *
     * @mbggenerated
     */
    public Float getEndSec() {
        return endSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route_price.end_sec
     *
     * @param endSec the value for sb_customer_vip_route_price.end_sec
     *
     * @mbggenerated
     */
    public void setEndSec(Float endSec) {
        this.endSec = endSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route_price.price
     *
     * @return the value of sb_customer_vip_route_price.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route_price.price
     *
     * @param price the value for sb_customer_vip_route_price.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}