package com.wangkuo.zxb.coreservice.db.po;

public class SbCustomerVipBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.is_tax
     *
     * @mbggenerated
     */
    private Integer isTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.is_load
     *
     * @mbggenerated
     */
    private Integer isLoad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.is_pack
     *
     * @mbggenerated
     */
    private Integer isPack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.is_upstairs
     *
     * @mbggenerated
     */
    private Integer isUpstairs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.is_depot
     *
     * @mbggenerated
     */
    private Integer isDepot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.day_balance_account
     *
     * @mbggenerated
     */
    private Integer dayBalanceAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.day_close_account
     *
     * @mbggenerated
     */
    private Integer dayCloseAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.day_open_ticket
     *
     * @mbggenerated
     */
    private Integer dayOpenTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_base.bank_no
     *
     * @mbggenerated
     */
    private String bankNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.id
     *
     * @return the value of sb_customer_vip_base.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.id
     *
     * @param id the value for sb_customer_vip_base.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.customer_id
     *
     * @return the value of sb_customer_vip_base.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.customer_id
     *
     * @param customerId the value for sb_customer_vip_base.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.is_tax
     *
     * @return the value of sb_customer_vip_base.is_tax
     *
     * @mbggenerated
     */
    public Integer getIsTax() {
        return isTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.is_tax
     *
     * @param isTax the value for sb_customer_vip_base.is_tax
     *
     * @mbggenerated
     */
    public void setIsTax(Integer isTax) {
        this.isTax = isTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.is_load
     *
     * @return the value of sb_customer_vip_base.is_load
     *
     * @mbggenerated
     */
    public Integer getIsLoad() {
        return isLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.is_load
     *
     * @param isLoad the value for sb_customer_vip_base.is_load
     *
     * @mbggenerated
     */
    public void setIsLoad(Integer isLoad) {
        this.isLoad = isLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.is_pack
     *
     * @return the value of sb_customer_vip_base.is_pack
     *
     * @mbggenerated
     */
    public Integer getIsPack() {
        return isPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.is_pack
     *
     * @param isPack the value for sb_customer_vip_base.is_pack
     *
     * @mbggenerated
     */
    public void setIsPack(Integer isPack) {
        this.isPack = isPack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.is_upstairs
     *
     * @return the value of sb_customer_vip_base.is_upstairs
     *
     * @mbggenerated
     */
    public Integer getIsUpstairs() {
        return isUpstairs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.is_upstairs
     *
     * @param isUpstairs the value for sb_customer_vip_base.is_upstairs
     *
     * @mbggenerated
     */
    public void setIsUpstairs(Integer isUpstairs) {
        this.isUpstairs = isUpstairs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.is_depot
     *
     * @return the value of sb_customer_vip_base.is_depot
     *
     * @mbggenerated
     */
    public Integer getIsDepot() {
        return isDepot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.is_depot
     *
     * @param isDepot the value for sb_customer_vip_base.is_depot
     *
     * @mbggenerated
     */
    public void setIsDepot(Integer isDepot) {
        this.isDepot = isDepot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.day_balance_account
     *
     * @return the value of sb_customer_vip_base.day_balance_account
     *
     * @mbggenerated
     */
    public Integer getDayBalanceAccount() {
        return dayBalanceAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.day_balance_account
     *
     * @param dayBalanceAccount the value for sb_customer_vip_base.day_balance_account
     *
     * @mbggenerated
     */
    public void setDayBalanceAccount(Integer dayBalanceAccount) {
        this.dayBalanceAccount = dayBalanceAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.day_close_account
     *
     * @return the value of sb_customer_vip_base.day_close_account
     *
     * @mbggenerated
     */
    public Integer getDayCloseAccount() {
        return dayCloseAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.day_close_account
     *
     * @param dayCloseAccount the value for sb_customer_vip_base.day_close_account
     *
     * @mbggenerated
     */
    public void setDayCloseAccount(Integer dayCloseAccount) {
        this.dayCloseAccount = dayCloseAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.day_open_ticket
     *
     * @return the value of sb_customer_vip_base.day_open_ticket
     *
     * @mbggenerated
     */
    public Integer getDayOpenTicket() {
        return dayOpenTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.day_open_ticket
     *
     * @param dayOpenTicket the value for sb_customer_vip_base.day_open_ticket
     *
     * @mbggenerated
     */
    public void setDayOpenTicket(Integer dayOpenTicket) {
        this.dayOpenTicket = dayOpenTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.bank_name
     *
     * @return the value of sb_customer_vip_base.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.bank_name
     *
     * @param bankName the value for sb_customer_vip_base.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.account_name
     *
     * @return the value of sb_customer_vip_base.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.account_name
     *
     * @param accountName the value for sb_customer_vip_base.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_base.bank_no
     *
     * @return the value of sb_customer_vip_base.bank_no
     *
     * @mbggenerated
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_base.bank_no
     *
     * @param bankNo the value for sb_customer_vip_base.bank_no
     *
     * @mbggenerated
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }
}