package com.wangkuo.zxb.coreservice.db.po;

public class SbCustomerVipGood {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good.good_type
     *
     * @mbggenerated
     */
    private Integer goodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good.good_name
     *
     * @mbggenerated
     */
    private String goodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good.good_space
     *
     * @mbggenerated
     */
    private String goodSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good.goods_pack_type
     *
     * @mbggenerated
     */
    private String goodsPackType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good.goods_stack_type
     *
     * @mbggenerated
     */
    private String goodsStackType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_good.goods_handling_type
     *
     * @mbggenerated
     */
    private String goodsHandlingType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good.id
     *
     * @return the value of sb_customer_vip_good.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good.id
     *
     * @param id the value for sb_customer_vip_good.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good.customer_id
     *
     * @return the value of sb_customer_vip_good.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good.customer_id
     *
     * @param customerId the value for sb_customer_vip_good.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good.good_type
     *
     * @return the value of sb_customer_vip_good.good_type
     *
     * @mbggenerated
     */
    public Integer getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good.good_type
     *
     * @param goodType the value for sb_customer_vip_good.good_type
     *
     * @mbggenerated
     */
    public void setGoodType(Integer goodType) {
        this.goodType = goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good.good_name
     *
     * @return the value of sb_customer_vip_good.good_name
     *
     * @mbggenerated
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good.good_name
     *
     * @param goodName the value for sb_customer_vip_good.good_name
     *
     * @mbggenerated
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName == null ? null : goodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good.good_space
     *
     * @return the value of sb_customer_vip_good.good_space
     *
     * @mbggenerated
     */
    public String getGoodSpace() {
        return goodSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good.good_space
     *
     * @param goodSpace the value for sb_customer_vip_good.good_space
     *
     * @mbggenerated
     */
    public void setGoodSpace(String goodSpace) {
        this.goodSpace = goodSpace == null ? null : goodSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good.goods_pack_type
     *
     * @return the value of sb_customer_vip_good.goods_pack_type
     *
     * @mbggenerated
     */
    public String getGoodsPackType() {
        return goodsPackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good.goods_pack_type
     *
     * @param goodsPackType the value for sb_customer_vip_good.goods_pack_type
     *
     * @mbggenerated
     */
    public void setGoodsPackType(String goodsPackType) {
        this.goodsPackType = goodsPackType == null ? null : goodsPackType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good.goods_stack_type
     *
     * @return the value of sb_customer_vip_good.goods_stack_type
     *
     * @mbggenerated
     */
    public String getGoodsStackType() {
        return goodsStackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good.goods_stack_type
     *
     * @param goodsStackType the value for sb_customer_vip_good.goods_stack_type
     *
     * @mbggenerated
     */
    public void setGoodsStackType(String goodsStackType) {
        this.goodsStackType = goodsStackType == null ? null : goodsStackType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_good.goods_handling_type
     *
     * @return the value of sb_customer_vip_good.goods_handling_type
     *
     * @mbggenerated
     */
    public String getGoodsHandlingType() {
        return goodsHandlingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_good.goods_handling_type
     *
     * @param goodsHandlingType the value for sb_customer_vip_good.goods_handling_type
     *
     * @mbggenerated
     */
    public void setGoodsHandlingType(String goodsHandlingType) {
        this.goodsHandlingType = goodsHandlingType == null ? null : goodsHandlingType.trim();
    }
}