package com.wangkuo.zxb.coreservice.db.po;

import java.util.Date;

public class SbCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.customer_code
     *
     * @mbggenerated
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.linkman
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.linkman_phone
     *
     * @mbggenerated
     */
    private String linkmanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.province_id
     *
     * @mbggenerated
     */
    private Long provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.city_id
     *
     * @mbggenerated
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.country_name
     *
     * @mbggenerated
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.country_id
     *
     * @mbggenerated
     */
    private Long countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.booker_employee_id
     *
     * @mbggenerated
     */
    private Long bookerEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.booker_employee_name
     *
     * @mbggenerated
     */
    private String bookerEmployeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.down_id
     *
     * @mbggenerated
     */
    private String downId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.site_id
     *
     * @mbggenerated
     */
    private Long siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.customer_account
     *
     * @mbggenerated
     */
    private String customerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer.is_vip_change
     *
     * @mbggenerated
     */
    private Integer isVipChange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.id
     *
     * @return the value of sb_customer.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.id
     *
     * @param id the value for sb_customer.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.customer_code
     *
     * @return the value of sb_customer.customer_code
     *
     * @mbggenerated
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.customer_code
     *
     * @param customerCode the value for sb_customer.customer_code
     *
     * @mbggenerated
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.customer_name
     *
     * @return the value of sb_customer.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.customer_name
     *
     * @param customerName the value for sb_customer.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.status
     *
     * @return the value of sb_customer.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.status
     *
     * @param status the value for sb_customer.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.linkman
     *
     * @return the value of sb_customer.linkman
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.linkman
     *
     * @param linkman the value for sb_customer.linkman
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.linkman_phone
     *
     * @return the value of sb_customer.linkman_phone
     *
     * @mbggenerated
     */
    public String getLinkmanPhone() {
        return linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.linkman_phone
     *
     * @param linkmanPhone the value for sb_customer.linkman_phone
     *
     * @mbggenerated
     */
    public void setLinkmanPhone(String linkmanPhone) {
        this.linkmanPhone = linkmanPhone == null ? null : linkmanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.province_name
     *
     * @return the value of sb_customer.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.province_name
     *
     * @param provinceName the value for sb_customer.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.province_id
     *
     * @return the value of sb_customer.province_id
     *
     * @mbggenerated
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.province_id
     *
     * @param provinceId the value for sb_customer.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.city_name
     *
     * @return the value of sb_customer.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.city_name
     *
     * @param cityName the value for sb_customer.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.city_id
     *
     * @return the value of sb_customer.city_id
     *
     * @mbggenerated
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.city_id
     *
     * @param cityId the value for sb_customer.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.country_name
     *
     * @return the value of sb_customer.country_name
     *
     * @mbggenerated
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.country_name
     *
     * @param countryName the value for sb_customer.country_name
     *
     * @mbggenerated
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.country_id
     *
     * @return the value of sb_customer.country_id
     *
     * @mbggenerated
     */
    public Long getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.country_id
     *
     * @param countryId the value for sb_customer.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.address
     *
     * @return the value of sb_customer.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.address
     *
     * @param address the value for sb_customer.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.booker_employee_id
     *
     * @return the value of sb_customer.booker_employee_id
     *
     * @mbggenerated
     */
    public Long getBookerEmployeeId() {
        return bookerEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.booker_employee_id
     *
     * @param bookerEmployeeId the value for sb_customer.booker_employee_id
     *
     * @mbggenerated
     */
    public void setBookerEmployeeId(Long bookerEmployeeId) {
        this.bookerEmployeeId = bookerEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.booker_employee_name
     *
     * @return the value of sb_customer.booker_employee_name
     *
     * @mbggenerated
     */
    public String getBookerEmployeeName() {
        return bookerEmployeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.booker_employee_name
     *
     * @param bookerEmployeeName the value for sb_customer.booker_employee_name
     *
     * @mbggenerated
     */
    public void setBookerEmployeeName(String bookerEmployeeName) {
        this.bookerEmployeeName = bookerEmployeeName == null ? null : bookerEmployeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.create_time
     *
     * @return the value of sb_customer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.create_time
     *
     * @param createTime the value for sb_customer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.memo
     *
     * @return the value of sb_customer.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.memo
     *
     * @param memo the value for sb_customer.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.down_id
     *
     * @return the value of sb_customer.down_id
     *
     * @mbggenerated
     */
    public String getDownId() {
        return downId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.down_id
     *
     * @param downId the value for sb_customer.down_id
     *
     * @mbggenerated
     */
    public void setDownId(String downId) {
        this.downId = downId == null ? null : downId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.site_id
     *
     * @return the value of sb_customer.site_id
     *
     * @mbggenerated
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.site_id
     *
     * @param siteId the value for sb_customer.site_id
     *
     * @mbggenerated
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.customer_account
     *
     * @return the value of sb_customer.customer_account
     *
     * @mbggenerated
     */
    public String getCustomerAccount() {
        return customerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.customer_account
     *
     * @param customerAccount the value for sb_customer.customer_account
     *
     * @mbggenerated
     */
    public void setCustomerAccount(String customerAccount) {
        this.customerAccount = customerAccount == null ? null : customerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.type
     *
     * @return the value of sb_customer.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.type
     *
     * @param type the value for sb_customer.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer.is_vip_change
     *
     * @return the value of sb_customer.is_vip_change
     *
     * @mbggenerated
     */
    public Integer getIsVipChange() {
        return isVipChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer.is_vip_change
     *
     * @param isVipChange the value for sb_customer.is_vip_change
     *
     * @mbggenerated
     */
    public void setIsVipChange(Integer isVipChange) {
        this.isVipChange = isVipChange;
    }
}