package com.wangkuo.zxb.coreservice.db.po;

public class SbCustomerVipRoute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.end_province_id
     *
     * @mbggenerated
     */
    private Long endProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.end_province_name
     *
     * @mbggenerated
     */
    private String endProvinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.end_city_id
     *
     * @mbggenerated
     */
    private Long endCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.end_city_name
     *
     * @mbggenerated
     */
    private String endCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.end_country_id
     *
     * @mbggenerated
     */
    private Long endCountryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.end_country_name
     *
     * @mbggenerated
     */
    private String endCountryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_customer_vip_route.hours_limit
     *
     * @mbggenerated
     */
    private Integer hoursLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.id
     *
     * @return the value of sb_customer_vip_route.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.id
     *
     * @param id the value for sb_customer_vip_route.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.customer_id
     *
     * @return the value of sb_customer_vip_route.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.customer_id
     *
     * @param customerId the value for sb_customer_vip_route.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.end_province_id
     *
     * @return the value of sb_customer_vip_route.end_province_id
     *
     * @mbggenerated
     */
    public Long getEndProvinceId() {
        return endProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.end_province_id
     *
     * @param endProvinceId the value for sb_customer_vip_route.end_province_id
     *
     * @mbggenerated
     */
    public void setEndProvinceId(Long endProvinceId) {
        this.endProvinceId = endProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.end_province_name
     *
     * @return the value of sb_customer_vip_route.end_province_name
     *
     * @mbggenerated
     */
    public String getEndProvinceName() {
        return endProvinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.end_province_name
     *
     * @param endProvinceName the value for sb_customer_vip_route.end_province_name
     *
     * @mbggenerated
     */
    public void setEndProvinceName(String endProvinceName) {
        this.endProvinceName = endProvinceName == null ? null : endProvinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.end_city_id
     *
     * @return the value of sb_customer_vip_route.end_city_id
     *
     * @mbggenerated
     */
    public Long getEndCityId() {
        return endCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.end_city_id
     *
     * @param endCityId the value for sb_customer_vip_route.end_city_id
     *
     * @mbggenerated
     */
    public void setEndCityId(Long endCityId) {
        this.endCityId = endCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.end_city_name
     *
     * @return the value of sb_customer_vip_route.end_city_name
     *
     * @mbggenerated
     */
    public String getEndCityName() {
        return endCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.end_city_name
     *
     * @param endCityName the value for sb_customer_vip_route.end_city_name
     *
     * @mbggenerated
     */
    public void setEndCityName(String endCityName) {
        this.endCityName = endCityName == null ? null : endCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.end_country_id
     *
     * @return the value of sb_customer_vip_route.end_country_id
     *
     * @mbggenerated
     */
    public Long getEndCountryId() {
        return endCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.end_country_id
     *
     * @param endCountryId the value for sb_customer_vip_route.end_country_id
     *
     * @mbggenerated
     */
    public void setEndCountryId(Long endCountryId) {
        this.endCountryId = endCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.end_country_name
     *
     * @return the value of sb_customer_vip_route.end_country_name
     *
     * @mbggenerated
     */
    public String getEndCountryName() {
        return endCountryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.end_country_name
     *
     * @param endCountryName the value for sb_customer_vip_route.end_country_name
     *
     * @mbggenerated
     */
    public void setEndCountryName(String endCountryName) {
        this.endCountryName = endCountryName == null ? null : endCountryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_customer_vip_route.hours_limit
     *
     * @return the value of sb_customer_vip_route.hours_limit
     *
     * @mbggenerated
     */
    public Integer getHoursLimit() {
        return hoursLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_customer_vip_route.hours_limit
     *
     * @param hoursLimit the value for sb_customer_vip_route.hours_limit
     *
     * @mbggenerated
     */
    public void setHoursLimit(Integer hoursLimit) {
        this.hoursLimit = hoursLimit;
    }
}