package com.wangkuo.zxb.coreservice.db.po;

import java.util.Date;

public class SbWaybill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.system_sn
     *
     * @mbggenerated
     */
    private String systemSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.sn
     *
     * @mbggenerated
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.operation_time
     *
     * @mbggenerated
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.site_id
     *
     * @mbggenerated
     */
    private Long siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.site_name
     *
     * @mbggenerated
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.alloc_center_id
     *
     * @mbggenerated
     */
    private Long allocCenterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.alloc_center_name
     *
     * @mbggenerated
     */
    private String allocCenterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_customer_id
     *
     * @mbggenerated
     */
    private Long shipperCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_customer_code
     *
     * @mbggenerated
     */
    private String shipperCustomerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_customer_name
     *
     * @mbggenerated
     */
    private String shipperCustomerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_province_id
     *
     * @mbggenerated
     */
    private Long shipperProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_province_name
     *
     * @mbggenerated
     */
    private String shipperProvinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_city_id
     *
     * @mbggenerated
     */
    private Long shipperCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_city_name
     *
     * @mbggenerated
     */
    private String shipperCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_country_id
     *
     * @mbggenerated
     */
    private Long shipperCountryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_country_name
     *
     * @mbggenerated
     */
    private String shipperCountryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_address
     *
     * @mbggenerated
     */
    private String shipperAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_link_name
     *
     * @mbggenerated
     */
    private String shipperLinkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.shipper_link_phone
     *
     * @mbggenerated
     */
    private String shipperLinkPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_name
     *
     * @mbggenerated
     */
    private String receiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_province_id
     *
     * @mbggenerated
     */
    private Long receiveProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_province_name
     *
     * @mbggenerated
     */
    private String receiveProvinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_city_id
     *
     * @mbggenerated
     */
    private Long receiveCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_city_name
     *
     * @mbggenerated
     */
    private String receiveCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_country_id
     *
     * @mbggenerated
     */
    private Long receiveCountryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_country_name
     *
     * @mbggenerated
     */
    private String receiveCountryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_address
     *
     * @mbggenerated
     */
    private String receiveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_link_name
     *
     * @mbggenerated
     */
    private String receiveLinkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receive_link_phone
     *
     * @mbggenerated
     */
    private String receiveLinkPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.is_damage
     *
     * @mbggenerated
     */
    private Integer isDamage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.is_change
     *
     * @mbggenerated
     */
    private Integer isChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.delete_reason_id
     *
     * @mbggenerated
     */
    private Long deleteReasonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.delete_reason
     *
     * @mbggenerated
     */
    private String deleteReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.delete_reason_memo
     *
     * @mbggenerated
     */
    private String deleteReasonMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.connect_type
     *
     * @mbggenerated
     */
    private Integer connectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.other_connect_type
     *
     * @mbggenerated
     */
    private String otherConnectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.balance_type
     *
     * @mbggenerated
     */
    private Integer balanceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.is_need_receipt
     *
     * @mbggenerated
     */
    private Integer isNeedReceipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.is_open_ticket
     *
     * @mbggenerated
     */
    private Integer isOpenTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.ticket_name
     *
     * @mbggenerated
     */
    private String ticketName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.load_unload_type
     *
     * @mbggenerated
     */
    private Integer loadUnloadType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.stack_require
     *
     * @mbggenerated
     */
    private String stackRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.delivery_type
     *
     * @mbggenerated
     */
    private Integer deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.trans_confir_time
     *
     * @mbggenerated
     */
    private Date transConfirTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.arrange_delivery_time
     *
     * @mbggenerated
     */
    private Date arrangeDeliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.good_station_time
     *
     * @mbggenerated
     */
    private Date goodStationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.time_require
     *
     * @mbggenerated
     */
    private Float timeRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.expect_arrival_time
     *
     * @mbggenerated
     */
    private Date expectArrivalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.expect_stowage_time
     *
     * @mbggenerated
     */
    private Date expectStowageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.back_status
     *
     * @mbggenerated
     */
    private Integer backStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.back_memo
     *
     * @mbggenerated
     */
    private String backMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.back_submit_user_id
     *
     * @mbggenerated
     */
    private Long backSubmitUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.back_submit_user_name
     *
     * @mbggenerated
     */
    private String backSubmitUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.back_submit_time
     *
     * @mbggenerated
     */
    private Date backSubmitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.back_receive_user_id
     *
     * @mbggenerated
     */
    private Long backReceiveUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.back_receive_user_name
     *
     * @mbggenerated
     */
    private String backReceiveUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.back_receive_time
     *
     * @mbggenerated
     */
    private Date backReceiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.booker_employee_id
     *
     * @mbggenerated
     */
    private Long bookerEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.booker_employee_name
     *
     * @mbggenerated
     */
    private String bookerEmployeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.business_id
     *
     * @mbggenerated
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.business_name
     *
     * @mbggenerated
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.is_receive_send_sms
     *
     * @mbggenerated
     */
    private Integer isReceiveSendSms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.down_id
     *
     * @mbggenerated
     */
    private String downId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.is_local
     *
     * @mbggenerated
     */
    private Integer isLocal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.balance_status
     *
     * @mbggenerated
     */
    private Integer balanceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.pay_status
     *
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.pay_locked
     *
     * @mbggenerated
     */
    private Integer payLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.receipt_time
     *
     * @mbggenerated
     */
    private Integer receiptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.is_need_enter_depot
     *
     * @mbggenerated
     */
    private Integer isNeedEnterDepot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.sign_time
     *
     * @mbggenerated
     */
    private Date signTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.sign_user_id
     *
     * @mbggenerated
     */
    private Long signUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sb_waybill.sign_user_name
     *
     * @mbggenerated
     */
    private String signUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.id
     *
     * @return the value of sb_waybill.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.id
     *
     * @param id the value for sb_waybill.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.system_sn
     *
     * @return the value of sb_waybill.system_sn
     *
     * @mbggenerated
     */
    public String getSystemSn() {
        return systemSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.system_sn
     *
     * @param systemSn the value for sb_waybill.system_sn
     *
     * @mbggenerated
     */
    public void setSystemSn(String systemSn) {
        this.systemSn = systemSn == null ? null : systemSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.sn
     *
     * @return the value of sb_waybill.sn
     *
     * @mbggenerated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.sn
     *
     * @param sn the value for sb_waybill.sn
     *
     * @mbggenerated
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.operation_time
     *
     * @return the value of sb_waybill.operation_time
     *
     * @mbggenerated
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.operation_time
     *
     * @param operationTime the value for sb_waybill.operation_time
     *
     * @mbggenerated
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.status
     *
     * @return the value of sb_waybill.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.status
     *
     * @param status the value for sb_waybill.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.source
     *
     * @return the value of sb_waybill.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.source
     *
     * @param source the value for sb_waybill.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.site_id
     *
     * @return the value of sb_waybill.site_id
     *
     * @mbggenerated
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.site_id
     *
     * @param siteId the value for sb_waybill.site_id
     *
     * @mbggenerated
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.site_name
     *
     * @return the value of sb_waybill.site_name
     *
     * @mbggenerated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.site_name
     *
     * @param siteName the value for sb_waybill.site_name
     *
     * @mbggenerated
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.alloc_center_id
     *
     * @return the value of sb_waybill.alloc_center_id
     *
     * @mbggenerated
     */
    public Long getAllocCenterId() {
        return allocCenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.alloc_center_id
     *
     * @param allocCenterId the value for sb_waybill.alloc_center_id
     *
     * @mbggenerated
     */
    public void setAllocCenterId(Long allocCenterId) {
        this.allocCenterId = allocCenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.alloc_center_name
     *
     * @return the value of sb_waybill.alloc_center_name
     *
     * @mbggenerated
     */
    public String getAllocCenterName() {
        return allocCenterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.alloc_center_name
     *
     * @param allocCenterName the value for sb_waybill.alloc_center_name
     *
     * @mbggenerated
     */
    public void setAllocCenterName(String allocCenterName) {
        this.allocCenterName = allocCenterName == null ? null : allocCenterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_customer_id
     *
     * @return the value of sb_waybill.shipper_customer_id
     *
     * @mbggenerated
     */
    public Long getShipperCustomerId() {
        return shipperCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_customer_id
     *
     * @param shipperCustomerId the value for sb_waybill.shipper_customer_id
     *
     * @mbggenerated
     */
    public void setShipperCustomerId(Long shipperCustomerId) {
        this.shipperCustomerId = shipperCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_customer_code
     *
     * @return the value of sb_waybill.shipper_customer_code
     *
     * @mbggenerated
     */
    public String getShipperCustomerCode() {
        return shipperCustomerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_customer_code
     *
     * @param shipperCustomerCode the value for sb_waybill.shipper_customer_code
     *
     * @mbggenerated
     */
    public void setShipperCustomerCode(String shipperCustomerCode) {
        this.shipperCustomerCode = shipperCustomerCode == null ? null : shipperCustomerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_customer_name
     *
     * @return the value of sb_waybill.shipper_customer_name
     *
     * @mbggenerated
     */
    public String getShipperCustomerName() {
        return shipperCustomerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_customer_name
     *
     * @param shipperCustomerName the value for sb_waybill.shipper_customer_name
     *
     * @mbggenerated
     */
    public void setShipperCustomerName(String shipperCustomerName) {
        this.shipperCustomerName = shipperCustomerName == null ? null : shipperCustomerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_province_id
     *
     * @return the value of sb_waybill.shipper_province_id
     *
     * @mbggenerated
     */
    public Long getShipperProvinceId() {
        return shipperProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_province_id
     *
     * @param shipperProvinceId the value for sb_waybill.shipper_province_id
     *
     * @mbggenerated
     */
    public void setShipperProvinceId(Long shipperProvinceId) {
        this.shipperProvinceId = shipperProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_province_name
     *
     * @return the value of sb_waybill.shipper_province_name
     *
     * @mbggenerated
     */
    public String getShipperProvinceName() {
        return shipperProvinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_province_name
     *
     * @param shipperProvinceName the value for sb_waybill.shipper_province_name
     *
     * @mbggenerated
     */
    public void setShipperProvinceName(String shipperProvinceName) {
        this.shipperProvinceName = shipperProvinceName == null ? null : shipperProvinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_city_id
     *
     * @return the value of sb_waybill.shipper_city_id
     *
     * @mbggenerated
     */
    public Long getShipperCityId() {
        return shipperCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_city_id
     *
     * @param shipperCityId the value for sb_waybill.shipper_city_id
     *
     * @mbggenerated
     */
    public void setShipperCityId(Long shipperCityId) {
        this.shipperCityId = shipperCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_city_name
     *
     * @return the value of sb_waybill.shipper_city_name
     *
     * @mbggenerated
     */
    public String getShipperCityName() {
        return shipperCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_city_name
     *
     * @param shipperCityName the value for sb_waybill.shipper_city_name
     *
     * @mbggenerated
     */
    public void setShipperCityName(String shipperCityName) {
        this.shipperCityName = shipperCityName == null ? null : shipperCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_country_id
     *
     * @return the value of sb_waybill.shipper_country_id
     *
     * @mbggenerated
     */
    public Long getShipperCountryId() {
        return shipperCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_country_id
     *
     * @param shipperCountryId the value for sb_waybill.shipper_country_id
     *
     * @mbggenerated
     */
    public void setShipperCountryId(Long shipperCountryId) {
        this.shipperCountryId = shipperCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_country_name
     *
     * @return the value of sb_waybill.shipper_country_name
     *
     * @mbggenerated
     */
    public String getShipperCountryName() {
        return shipperCountryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_country_name
     *
     * @param shipperCountryName the value for sb_waybill.shipper_country_name
     *
     * @mbggenerated
     */
    public void setShipperCountryName(String shipperCountryName) {
        this.shipperCountryName = shipperCountryName == null ? null : shipperCountryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_address
     *
     * @return the value of sb_waybill.shipper_address
     *
     * @mbggenerated
     */
    public String getShipperAddress() {
        return shipperAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_address
     *
     * @param shipperAddress the value for sb_waybill.shipper_address
     *
     * @mbggenerated
     */
    public void setShipperAddress(String shipperAddress) {
        this.shipperAddress = shipperAddress == null ? null : shipperAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_link_name
     *
     * @return the value of sb_waybill.shipper_link_name
     *
     * @mbggenerated
     */
    public String getShipperLinkName() {
        return shipperLinkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_link_name
     *
     * @param shipperLinkName the value for sb_waybill.shipper_link_name
     *
     * @mbggenerated
     */
    public void setShipperLinkName(String shipperLinkName) {
        this.shipperLinkName = shipperLinkName == null ? null : shipperLinkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.shipper_link_phone
     *
     * @return the value of sb_waybill.shipper_link_phone
     *
     * @mbggenerated
     */
    public String getShipperLinkPhone() {
        return shipperLinkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.shipper_link_phone
     *
     * @param shipperLinkPhone the value for sb_waybill.shipper_link_phone
     *
     * @mbggenerated
     */
    public void setShipperLinkPhone(String shipperLinkPhone) {
        this.shipperLinkPhone = shipperLinkPhone == null ? null : shipperLinkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_name
     *
     * @return the value of sb_waybill.receive_name
     *
     * @mbggenerated
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_name
     *
     * @param receiveName the value for sb_waybill.receive_name
     *
     * @mbggenerated
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_province_id
     *
     * @return the value of sb_waybill.receive_province_id
     *
     * @mbggenerated
     */
    public Long getReceiveProvinceId() {
        return receiveProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_province_id
     *
     * @param receiveProvinceId the value for sb_waybill.receive_province_id
     *
     * @mbggenerated
     */
    public void setReceiveProvinceId(Long receiveProvinceId) {
        this.receiveProvinceId = receiveProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_province_name
     *
     * @return the value of sb_waybill.receive_province_name
     *
     * @mbggenerated
     */
    public String getReceiveProvinceName() {
        return receiveProvinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_province_name
     *
     * @param receiveProvinceName the value for sb_waybill.receive_province_name
     *
     * @mbggenerated
     */
    public void setReceiveProvinceName(String receiveProvinceName) {
        this.receiveProvinceName = receiveProvinceName == null ? null : receiveProvinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_city_id
     *
     * @return the value of sb_waybill.receive_city_id
     *
     * @mbggenerated
     */
    public Long getReceiveCityId() {
        return receiveCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_city_id
     *
     * @param receiveCityId the value for sb_waybill.receive_city_id
     *
     * @mbggenerated
     */
    public void setReceiveCityId(Long receiveCityId) {
        this.receiveCityId = receiveCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_city_name
     *
     * @return the value of sb_waybill.receive_city_name
     *
     * @mbggenerated
     */
    public String getReceiveCityName() {
        return receiveCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_city_name
     *
     * @param receiveCityName the value for sb_waybill.receive_city_name
     *
     * @mbggenerated
     */
    public void setReceiveCityName(String receiveCityName) {
        this.receiveCityName = receiveCityName == null ? null : receiveCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_country_id
     *
     * @return the value of sb_waybill.receive_country_id
     *
     * @mbggenerated
     */
    public Long getReceiveCountryId() {
        return receiveCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_country_id
     *
     * @param receiveCountryId the value for sb_waybill.receive_country_id
     *
     * @mbggenerated
     */
    public void setReceiveCountryId(Long receiveCountryId) {
        this.receiveCountryId = receiveCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_country_name
     *
     * @return the value of sb_waybill.receive_country_name
     *
     * @mbggenerated
     */
    public String getReceiveCountryName() {
        return receiveCountryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_country_name
     *
     * @param receiveCountryName the value for sb_waybill.receive_country_name
     *
     * @mbggenerated
     */
    public void setReceiveCountryName(String receiveCountryName) {
        this.receiveCountryName = receiveCountryName == null ? null : receiveCountryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_address
     *
     * @return the value of sb_waybill.receive_address
     *
     * @mbggenerated
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_address
     *
     * @param receiveAddress the value for sb_waybill.receive_address
     *
     * @mbggenerated
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_link_name
     *
     * @return the value of sb_waybill.receive_link_name
     *
     * @mbggenerated
     */
    public String getReceiveLinkName() {
        return receiveLinkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_link_name
     *
     * @param receiveLinkName the value for sb_waybill.receive_link_name
     *
     * @mbggenerated
     */
    public void setReceiveLinkName(String receiveLinkName) {
        this.receiveLinkName = receiveLinkName == null ? null : receiveLinkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receive_link_phone
     *
     * @return the value of sb_waybill.receive_link_phone
     *
     * @mbggenerated
     */
    public String getReceiveLinkPhone() {
        return receiveLinkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receive_link_phone
     *
     * @param receiveLinkPhone the value for sb_waybill.receive_link_phone
     *
     * @mbggenerated
     */
    public void setReceiveLinkPhone(String receiveLinkPhone) {
        this.receiveLinkPhone = receiveLinkPhone == null ? null : receiveLinkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.is_damage
     *
     * @return the value of sb_waybill.is_damage
     *
     * @mbggenerated
     */
    public Integer getIsDamage() {
        return isDamage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.is_damage
     *
     * @param isDamage the value for sb_waybill.is_damage
     *
     * @mbggenerated
     */
    public void setIsDamage(Integer isDamage) {
        this.isDamage = isDamage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.is_change
     *
     * @return the value of sb_waybill.is_change
     *
     * @mbggenerated
     */
    public Integer getIsChange() {
        return isChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.is_change
     *
     * @param isChange the value for sb_waybill.is_change
     *
     * @mbggenerated
     */
    public void setIsChange(Integer isChange) {
        this.isChange = isChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.is_delete
     *
     * @return the value of sb_waybill.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.is_delete
     *
     * @param isDelete the value for sb_waybill.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.delete_reason_id
     *
     * @return the value of sb_waybill.delete_reason_id
     *
     * @mbggenerated
     */
    public Long getDeleteReasonId() {
        return deleteReasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.delete_reason_id
     *
     * @param deleteReasonId the value for sb_waybill.delete_reason_id
     *
     * @mbggenerated
     */
    public void setDeleteReasonId(Long deleteReasonId) {
        this.deleteReasonId = deleteReasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.delete_reason
     *
     * @return the value of sb_waybill.delete_reason
     *
     * @mbggenerated
     */
    public String getDeleteReason() {
        return deleteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.delete_reason
     *
     * @param deleteReason the value for sb_waybill.delete_reason
     *
     * @mbggenerated
     */
    public void setDeleteReason(String deleteReason) {
        this.deleteReason = deleteReason == null ? null : deleteReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.delete_reason_memo
     *
     * @return the value of sb_waybill.delete_reason_memo
     *
     * @mbggenerated
     */
    public String getDeleteReasonMemo() {
        return deleteReasonMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.delete_reason_memo
     *
     * @param deleteReasonMemo the value for sb_waybill.delete_reason_memo
     *
     * @mbggenerated
     */
    public void setDeleteReasonMemo(String deleteReasonMemo) {
        this.deleteReasonMemo = deleteReasonMemo == null ? null : deleteReasonMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.connect_type
     *
     * @return the value of sb_waybill.connect_type
     *
     * @mbggenerated
     */
    public Integer getConnectType() {
        return connectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.connect_type
     *
     * @param connectType the value for sb_waybill.connect_type
     *
     * @mbggenerated
     */
    public void setConnectType(Integer connectType) {
        this.connectType = connectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.other_connect_type
     *
     * @return the value of sb_waybill.other_connect_type
     *
     * @mbggenerated
     */
    public String getOtherConnectType() {
        return otherConnectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.other_connect_type
     *
     * @param otherConnectType the value for sb_waybill.other_connect_type
     *
     * @mbggenerated
     */
    public void setOtherConnectType(String otherConnectType) {
        this.otherConnectType = otherConnectType == null ? null : otherConnectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.balance_type
     *
     * @return the value of sb_waybill.balance_type
     *
     * @mbggenerated
     */
    public Integer getBalanceType() {
        return balanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.balance_type
     *
     * @param balanceType the value for sb_waybill.balance_type
     *
     * @mbggenerated
     */
    public void setBalanceType(Integer balanceType) {
        this.balanceType = balanceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.is_need_receipt
     *
     * @return the value of sb_waybill.is_need_receipt
     *
     * @mbggenerated
     */
    public Integer getIsNeedReceipt() {
        return isNeedReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.is_need_receipt
     *
     * @param isNeedReceipt the value for sb_waybill.is_need_receipt
     *
     * @mbggenerated
     */
    public void setIsNeedReceipt(Integer isNeedReceipt) {
        this.isNeedReceipt = isNeedReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.is_open_ticket
     *
     * @return the value of sb_waybill.is_open_ticket
     *
     * @mbggenerated
     */
    public Integer getIsOpenTicket() {
        return isOpenTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.is_open_ticket
     *
     * @param isOpenTicket the value for sb_waybill.is_open_ticket
     *
     * @mbggenerated
     */
    public void setIsOpenTicket(Integer isOpenTicket) {
        this.isOpenTicket = isOpenTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.ticket_name
     *
     * @return the value of sb_waybill.ticket_name
     *
     * @mbggenerated
     */
    public String getTicketName() {
        return ticketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.ticket_name
     *
     * @param ticketName the value for sb_waybill.ticket_name
     *
     * @mbggenerated
     */
    public void setTicketName(String ticketName) {
        this.ticketName = ticketName == null ? null : ticketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.load_unload_type
     *
     * @return the value of sb_waybill.load_unload_type
     *
     * @mbggenerated
     */
    public Integer getLoadUnloadType() {
        return loadUnloadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.load_unload_type
     *
     * @param loadUnloadType the value for sb_waybill.load_unload_type
     *
     * @mbggenerated
     */
    public void setLoadUnloadType(Integer loadUnloadType) {
        this.loadUnloadType = loadUnloadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.stack_require
     *
     * @return the value of sb_waybill.stack_require
     *
     * @mbggenerated
     */
    public String getStackRequire() {
        return stackRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.stack_require
     *
     * @param stackRequire the value for sb_waybill.stack_require
     *
     * @mbggenerated
     */
    public void setStackRequire(String stackRequire) {
        this.stackRequire = stackRequire == null ? null : stackRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.delivery_type
     *
     * @return the value of sb_waybill.delivery_type
     *
     * @mbggenerated
     */
    public Integer getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.delivery_type
     *
     * @param deliveryType the value for sb_waybill.delivery_type
     *
     * @mbggenerated
     */
    public void setDeliveryType(Integer deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.trans_confir_time
     *
     * @return the value of sb_waybill.trans_confir_time
     *
     * @mbggenerated
     */
    public Date getTransConfirTime() {
        return transConfirTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.trans_confir_time
     *
     * @param transConfirTime the value for sb_waybill.trans_confir_time
     *
     * @mbggenerated
     */
    public void setTransConfirTime(Date transConfirTime) {
        this.transConfirTime = transConfirTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.arrange_delivery_time
     *
     * @return the value of sb_waybill.arrange_delivery_time
     *
     * @mbggenerated
     */
    public Date getArrangeDeliveryTime() {
        return arrangeDeliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.arrange_delivery_time
     *
     * @param arrangeDeliveryTime the value for sb_waybill.arrange_delivery_time
     *
     * @mbggenerated
     */
    public void setArrangeDeliveryTime(Date arrangeDeliveryTime) {
        this.arrangeDeliveryTime = arrangeDeliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.good_station_time
     *
     * @return the value of sb_waybill.good_station_time
     *
     * @mbggenerated
     */
    public Date getGoodStationTime() {
        return goodStationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.good_station_time
     *
     * @param goodStationTime the value for sb_waybill.good_station_time
     *
     * @mbggenerated
     */
    public void setGoodStationTime(Date goodStationTime) {
        this.goodStationTime = goodStationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.time_require
     *
     * @return the value of sb_waybill.time_require
     *
     * @mbggenerated
     */
    public Float getTimeRequire() {
        return timeRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.time_require
     *
     * @param timeRequire the value for sb_waybill.time_require
     *
     * @mbggenerated
     */
    public void setTimeRequire(Float timeRequire) {
        this.timeRequire = timeRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.expect_arrival_time
     *
     * @return the value of sb_waybill.expect_arrival_time
     *
     * @mbggenerated
     */
    public Date getExpectArrivalTime() {
        return expectArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.expect_arrival_time
     *
     * @param expectArrivalTime the value for sb_waybill.expect_arrival_time
     *
     * @mbggenerated
     */
    public void setExpectArrivalTime(Date expectArrivalTime) {
        this.expectArrivalTime = expectArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.expect_stowage_time
     *
     * @return the value of sb_waybill.expect_stowage_time
     *
     * @mbggenerated
     */
    public Date getExpectStowageTime() {
        return expectStowageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.expect_stowage_time
     *
     * @param expectStowageTime the value for sb_waybill.expect_stowage_time
     *
     * @mbggenerated
     */
    public void setExpectStowageTime(Date expectStowageTime) {
        this.expectStowageTime = expectStowageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.memo
     *
     * @return the value of sb_waybill.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.memo
     *
     * @param memo the value for sb_waybill.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.back_status
     *
     * @return the value of sb_waybill.back_status
     *
     * @mbggenerated
     */
    public Integer getBackStatus() {
        return backStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.back_status
     *
     * @param backStatus the value for sb_waybill.back_status
     *
     * @mbggenerated
     */
    public void setBackStatus(Integer backStatus) {
        this.backStatus = backStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.back_memo
     *
     * @return the value of sb_waybill.back_memo
     *
     * @mbggenerated
     */
    public String getBackMemo() {
        return backMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.back_memo
     *
     * @param backMemo the value for sb_waybill.back_memo
     *
     * @mbggenerated
     */
    public void setBackMemo(String backMemo) {
        this.backMemo = backMemo == null ? null : backMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.back_submit_user_id
     *
     * @return the value of sb_waybill.back_submit_user_id
     *
     * @mbggenerated
     */
    public Long getBackSubmitUserId() {
        return backSubmitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.back_submit_user_id
     *
     * @param backSubmitUserId the value for sb_waybill.back_submit_user_id
     *
     * @mbggenerated
     */
    public void setBackSubmitUserId(Long backSubmitUserId) {
        this.backSubmitUserId = backSubmitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.back_submit_user_name
     *
     * @return the value of sb_waybill.back_submit_user_name
     *
     * @mbggenerated
     */
    public String getBackSubmitUserName() {
        return backSubmitUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.back_submit_user_name
     *
     * @param backSubmitUserName the value for sb_waybill.back_submit_user_name
     *
     * @mbggenerated
     */
    public void setBackSubmitUserName(String backSubmitUserName) {
        this.backSubmitUserName = backSubmitUserName == null ? null : backSubmitUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.back_submit_time
     *
     * @return the value of sb_waybill.back_submit_time
     *
     * @mbggenerated
     */
    public Date getBackSubmitTime() {
        return backSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.back_submit_time
     *
     * @param backSubmitTime the value for sb_waybill.back_submit_time
     *
     * @mbggenerated
     */
    public void setBackSubmitTime(Date backSubmitTime) {
        this.backSubmitTime = backSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.back_receive_user_id
     *
     * @return the value of sb_waybill.back_receive_user_id
     *
     * @mbggenerated
     */
    public Long getBackReceiveUserId() {
        return backReceiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.back_receive_user_id
     *
     * @param backReceiveUserId the value for sb_waybill.back_receive_user_id
     *
     * @mbggenerated
     */
    public void setBackReceiveUserId(Long backReceiveUserId) {
        this.backReceiveUserId = backReceiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.back_receive_user_name
     *
     * @return the value of sb_waybill.back_receive_user_name
     *
     * @mbggenerated
     */
    public String getBackReceiveUserName() {
        return backReceiveUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.back_receive_user_name
     *
     * @param backReceiveUserName the value for sb_waybill.back_receive_user_name
     *
     * @mbggenerated
     */
    public void setBackReceiveUserName(String backReceiveUserName) {
        this.backReceiveUserName = backReceiveUserName == null ? null : backReceiveUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.back_receive_time
     *
     * @return the value of sb_waybill.back_receive_time
     *
     * @mbggenerated
     */
    public Date getBackReceiveTime() {
        return backReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.back_receive_time
     *
     * @param backReceiveTime the value for sb_waybill.back_receive_time
     *
     * @mbggenerated
     */
    public void setBackReceiveTime(Date backReceiveTime) {
        this.backReceiveTime = backReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.booker_employee_id
     *
     * @return the value of sb_waybill.booker_employee_id
     *
     * @mbggenerated
     */
    public Long getBookerEmployeeId() {
        return bookerEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.booker_employee_id
     *
     * @param bookerEmployeeId the value for sb_waybill.booker_employee_id
     *
     * @mbggenerated
     */
    public void setBookerEmployeeId(Long bookerEmployeeId) {
        this.bookerEmployeeId = bookerEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.booker_employee_name
     *
     * @return the value of sb_waybill.booker_employee_name
     *
     * @mbggenerated
     */
    public String getBookerEmployeeName() {
        return bookerEmployeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.booker_employee_name
     *
     * @param bookerEmployeeName the value for sb_waybill.booker_employee_name
     *
     * @mbggenerated
     */
    public void setBookerEmployeeName(String bookerEmployeeName) {
        this.bookerEmployeeName = bookerEmployeeName == null ? null : bookerEmployeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.create_time
     *
     * @return the value of sb_waybill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.create_time
     *
     * @param createTime the value for sb_waybill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.business_id
     *
     * @return the value of sb_waybill.business_id
     *
     * @mbggenerated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.business_id
     *
     * @param businessId the value for sb_waybill.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.business_name
     *
     * @return the value of sb_waybill.business_name
     *
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.business_name
     *
     * @param businessName the value for sb_waybill.business_name
     *
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.is_receive_send_sms
     *
     * @return the value of sb_waybill.is_receive_send_sms
     *
     * @mbggenerated
     */
    public Integer getIsReceiveSendSms() {
        return isReceiveSendSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.is_receive_send_sms
     *
     * @param isReceiveSendSms the value for sb_waybill.is_receive_send_sms
     *
     * @mbggenerated
     */
    public void setIsReceiveSendSms(Integer isReceiveSendSms) {
        this.isReceiveSendSms = isReceiveSendSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.down_id
     *
     * @return the value of sb_waybill.down_id
     *
     * @mbggenerated
     */
    public String getDownId() {
        return downId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.down_id
     *
     * @param downId the value for sb_waybill.down_id
     *
     * @mbggenerated
     */
    public void setDownId(String downId) {
        this.downId = downId == null ? null : downId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.is_local
     *
     * @return the value of sb_waybill.is_local
     *
     * @mbggenerated
     */
    public Integer getIsLocal() {
        return isLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.is_local
     *
     * @param isLocal the value for sb_waybill.is_local
     *
     * @mbggenerated
     */
    public void setIsLocal(Integer isLocal) {
        this.isLocal = isLocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.balance_status
     *
     * @return the value of sb_waybill.balance_status
     *
     * @mbggenerated
     */
    public Integer getBalanceStatus() {
        return balanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.balance_status
     *
     * @param balanceStatus the value for sb_waybill.balance_status
     *
     * @mbggenerated
     */
    public void setBalanceStatus(Integer balanceStatus) {
        this.balanceStatus = balanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.pay_status
     *
     * @return the value of sb_waybill.pay_status
     *
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.pay_status
     *
     * @param payStatus the value for sb_waybill.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.pay_locked
     *
     * @return the value of sb_waybill.pay_locked
     *
     * @mbggenerated
     */
    public Integer getPayLocked() {
        return payLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.pay_locked
     *
     * @param payLocked the value for sb_waybill.pay_locked
     *
     * @mbggenerated
     */
    public void setPayLocked(Integer payLocked) {
        this.payLocked = payLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.receipt_time
     *
     * @return the value of sb_waybill.receipt_time
     *
     * @mbggenerated
     */
    public Integer getReceiptTime() {
        return receiptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.receipt_time
     *
     * @param receiptTime the value for sb_waybill.receipt_time
     *
     * @mbggenerated
     */
    public void setReceiptTime(Integer receiptTime) {
        this.receiptTime = receiptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.is_need_enter_depot
     *
     * @return the value of sb_waybill.is_need_enter_depot
     *
     * @mbggenerated
     */
    public Integer getIsNeedEnterDepot() {
        return isNeedEnterDepot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.is_need_enter_depot
     *
     * @param isNeedEnterDepot the value for sb_waybill.is_need_enter_depot
     *
     * @mbggenerated
     */
    public void setIsNeedEnterDepot(Integer isNeedEnterDepot) {
        this.isNeedEnterDepot = isNeedEnterDepot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.sign_time
     *
     * @return the value of sb_waybill.sign_time
     *
     * @mbggenerated
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.sign_time
     *
     * @param signTime the value for sb_waybill.sign_time
     *
     * @mbggenerated
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.sign_user_id
     *
     * @return the value of sb_waybill.sign_user_id
     *
     * @mbggenerated
     */
    public Long getSignUserId() {
        return signUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.sign_user_id
     *
     * @param signUserId the value for sb_waybill.sign_user_id
     *
     * @mbggenerated
     */
    public void setSignUserId(Long signUserId) {
        this.signUserId = signUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sb_waybill.sign_user_name
     *
     * @return the value of sb_waybill.sign_user_name
     *
     * @mbggenerated
     */
    public String getSignUserName() {
        return signUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sb_waybill.sign_user_name
     *
     * @param signUserName the value for sb_waybill.sign_user_name
     *
     * @mbggenerated
     */
    public void setSignUserName(String signUserName) {
        this.signUserName = signUserName == null ? null : signUserName.trim();
    }
}