package com.wangkuo.zxb.coreservice.db.po;

import java.math.BigDecimal;
import java.util.Date;

public class ZbSite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.site_code
     *
     * @mbggenerated
     */
    private String siteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.site_name
     *
     * @mbggenerated
     */
    private String siteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.province_id
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.country_name
     *
     * @mbggenerated
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.country_id
     *
     * @mbggenerated
     */
    private Integer countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.linkman
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.linkman_phone
     *
     * @mbggenerated
     */
    private String linkmanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.is__verify_sel_payment_apply
     *
     * @mbggenerated
     */
    private Integer isVerifySelPaymentApply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.premium_rate
     *
     * @mbggenerated
     */
    private Float premiumRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.give_premium_fee
     *
     * @mbggenerated
     */
    private BigDecimal givePremiumFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.current_balance
     *
     * @mbggenerated
     */
    private BigDecimal currentBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.booker_employee_id
     *
     * @mbggenerated
     */
    private Long bookerEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.booker_employee_name
     *
     * @mbggenerated
     */
    private String bookerEmployeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.is_min_fee_limit
     *
     * @mbggenerated
     */
    private Integer isMinFeeLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.down_id
     *
     * @mbggenerated
     */
    private String downId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.pay_time
     *
     * @mbggenerated
     */
    private Integer payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.late_fee_ratio
     *
     * @mbggenerated
     */
    private Float lateFeeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.is_must_xf
     *
     * @mbggenerated
     */
    private Integer isMustXf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.is_allow_hdf
     *
     * @mbggenerated
     */
    private Integer isAllowHdf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.hdf_fee_max_limit
     *
     * @mbggenerated
     */
    private BigDecimal hdfFeeMaxLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.premium_rate_with_zb
     *
     * @mbggenerated
     */
    private Float premiumRateWithZb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zb_site.is_allot_fee_limit_service_fee
     *
     * @mbggenerated
     */
    private Integer isAllotFeeLimitServiceFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.id
     *
     * @return the value of zb_site.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.id
     *
     * @param id the value for zb_site.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.site_code
     *
     * @return the value of zb_site.site_code
     *
     * @mbggenerated
     */
    public String getSiteCode() {
        return siteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.site_code
     *
     * @param siteCode the value for zb_site.site_code
     *
     * @mbggenerated
     */
    public void setSiteCode(String siteCode) {
        this.siteCode = siteCode == null ? null : siteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.site_name
     *
     * @return the value of zb_site.site_name
     *
     * @mbggenerated
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.site_name
     *
     * @param siteName the value for zb_site.site_name
     *
     * @mbggenerated
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.province_name
     *
     * @return the value of zb_site.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.province_name
     *
     * @param provinceName the value for zb_site.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.province_id
     *
     * @return the value of zb_site.province_id
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.province_id
     *
     * @param provinceId the value for zb_site.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.city_name
     *
     * @return the value of zb_site.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.city_name
     *
     * @param cityName the value for zb_site.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.city_id
     *
     * @return the value of zb_site.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.city_id
     *
     * @param cityId the value for zb_site.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.country_name
     *
     * @return the value of zb_site.country_name
     *
     * @mbggenerated
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.country_name
     *
     * @param countryName the value for zb_site.country_name
     *
     * @mbggenerated
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.country_id
     *
     * @return the value of zb_site.country_id
     *
     * @mbggenerated
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.country_id
     *
     * @param countryId the value for zb_site.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.address
     *
     * @return the value of zb_site.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.address
     *
     * @param address the value for zb_site.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.linkman
     *
     * @return the value of zb_site.linkman
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.linkman
     *
     * @param linkman the value for zb_site.linkman
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.linkman_phone
     *
     * @return the value of zb_site.linkman_phone
     *
     * @mbggenerated
     */
    public String getLinkmanPhone() {
        return linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.linkman_phone
     *
     * @param linkmanPhone the value for zb_site.linkman_phone
     *
     * @mbggenerated
     */
    public void setLinkmanPhone(String linkmanPhone) {
        this.linkmanPhone = linkmanPhone == null ? null : linkmanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.tel
     *
     * @return the value of zb_site.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.tel
     *
     * @param tel the value for zb_site.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.type
     *
     * @return the value of zb_site.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.type
     *
     * @param type the value for zb_site.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.is__verify_sel_payment_apply
     *
     * @return the value of zb_site.is__verify_sel_payment_apply
     *
     * @mbggenerated
     */
    public Integer getIsVerifySelPaymentApply() {
        return isVerifySelPaymentApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.is__verify_sel_payment_apply
     *
     * @param isVerifySelPaymentApply the value for zb_site.is__verify_sel_payment_apply
     *
     * @mbggenerated
     */
    public void setIsVerifySelPaymentApply(Integer isVerifySelPaymentApply) {
        this.isVerifySelPaymentApply = isVerifySelPaymentApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.premium_rate
     *
     * @return the value of zb_site.premium_rate
     *
     * @mbggenerated
     */
    public Float getPremiumRate() {
        return premiumRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.premium_rate
     *
     * @param premiumRate the value for zb_site.premium_rate
     *
     * @mbggenerated
     */
    public void setPremiumRate(Float premiumRate) {
        this.premiumRate = premiumRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.give_premium_fee
     *
     * @return the value of zb_site.give_premium_fee
     *
     * @mbggenerated
     */
    public BigDecimal getGivePremiumFee() {
        return givePremiumFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.give_premium_fee
     *
     * @param givePremiumFee the value for zb_site.give_premium_fee
     *
     * @mbggenerated
     */
    public void setGivePremiumFee(BigDecimal givePremiumFee) {
        this.givePremiumFee = givePremiumFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.current_balance
     *
     * @return the value of zb_site.current_balance
     *
     * @mbggenerated
     */
    public BigDecimal getCurrentBalance() {
        return currentBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.current_balance
     *
     * @param currentBalance the value for zb_site.current_balance
     *
     * @mbggenerated
     */
    public void setCurrentBalance(BigDecimal currentBalance) {
        this.currentBalance = currentBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.booker_employee_id
     *
     * @return the value of zb_site.booker_employee_id
     *
     * @mbggenerated
     */
    public Long getBookerEmployeeId() {
        return bookerEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.booker_employee_id
     *
     * @param bookerEmployeeId the value for zb_site.booker_employee_id
     *
     * @mbggenerated
     */
    public void setBookerEmployeeId(Long bookerEmployeeId) {
        this.bookerEmployeeId = bookerEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.booker_employee_name
     *
     * @return the value of zb_site.booker_employee_name
     *
     * @mbggenerated
     */
    public String getBookerEmployeeName() {
        return bookerEmployeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.booker_employee_name
     *
     * @param bookerEmployeeName the value for zb_site.booker_employee_name
     *
     * @mbggenerated
     */
    public void setBookerEmployeeName(String bookerEmployeeName) {
        this.bookerEmployeeName = bookerEmployeeName == null ? null : bookerEmployeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.create_time
     *
     * @return the value of zb_site.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.create_time
     *
     * @param createTime the value for zb_site.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.is_min_fee_limit
     *
     * @return the value of zb_site.is_min_fee_limit
     *
     * @mbggenerated
     */
    public Integer getIsMinFeeLimit() {
        return isMinFeeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.is_min_fee_limit
     *
     * @param isMinFeeLimit the value for zb_site.is_min_fee_limit
     *
     * @mbggenerated
     */
    public void setIsMinFeeLimit(Integer isMinFeeLimit) {
        this.isMinFeeLimit = isMinFeeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.down_id
     *
     * @return the value of zb_site.down_id
     *
     * @mbggenerated
     */
    public String getDownId() {
        return downId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.down_id
     *
     * @param downId the value for zb_site.down_id
     *
     * @mbggenerated
     */
    public void setDownId(String downId) {
        this.downId = downId == null ? null : downId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.pay_time
     *
     * @return the value of zb_site.pay_time
     *
     * @mbggenerated
     */
    public Integer getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.pay_time
     *
     * @param payTime the value for zb_site.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Integer payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.late_fee_ratio
     *
     * @return the value of zb_site.late_fee_ratio
     *
     * @mbggenerated
     */
    public Float getLateFeeRatio() {
        return lateFeeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.late_fee_ratio
     *
     * @param lateFeeRatio the value for zb_site.late_fee_ratio
     *
     * @mbggenerated
     */
    public void setLateFeeRatio(Float lateFeeRatio) {
        this.lateFeeRatio = lateFeeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.is_must_xf
     *
     * @return the value of zb_site.is_must_xf
     *
     * @mbggenerated
     */
    public Integer getIsMustXf() {
        return isMustXf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.is_must_xf
     *
     * @param isMustXf the value for zb_site.is_must_xf
     *
     * @mbggenerated
     */
    public void setIsMustXf(Integer isMustXf) {
        this.isMustXf = isMustXf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.is_allow_hdf
     *
     * @return the value of zb_site.is_allow_hdf
     *
     * @mbggenerated
     */
    public Integer getIsAllowHdf() {
        return isAllowHdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.is_allow_hdf
     *
     * @param isAllowHdf the value for zb_site.is_allow_hdf
     *
     * @mbggenerated
     */
    public void setIsAllowHdf(Integer isAllowHdf) {
        this.isAllowHdf = isAllowHdf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.hdf_fee_max_limit
     *
     * @return the value of zb_site.hdf_fee_max_limit
     *
     * @mbggenerated
     */
    public BigDecimal getHdfFeeMaxLimit() {
        return hdfFeeMaxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.hdf_fee_max_limit
     *
     * @param hdfFeeMaxLimit the value for zb_site.hdf_fee_max_limit
     *
     * @mbggenerated
     */
    public void setHdfFeeMaxLimit(BigDecimal hdfFeeMaxLimit) {
        this.hdfFeeMaxLimit = hdfFeeMaxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.premium_rate_with_zb
     *
     * @return the value of zb_site.premium_rate_with_zb
     *
     * @mbggenerated
     */
    public Float getPremiumRateWithZb() {
        return premiumRateWithZb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.premium_rate_with_zb
     *
     * @param premiumRateWithZb the value for zb_site.premium_rate_with_zb
     *
     * @mbggenerated
     */
    public void setPremiumRateWithZb(Float premiumRateWithZb) {
        this.premiumRateWithZb = premiumRateWithZb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zb_site.is_allot_fee_limit_service_fee
     *
     * @return the value of zb_site.is_allot_fee_limit_service_fee
     *
     * @mbggenerated
     */
    public Integer getIsAllotFeeLimitServiceFee() {
        return isAllotFeeLimitServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zb_site.is_allot_fee_limit_service_fee
     *
     * @param isAllotFeeLimitServiceFee the value for zb_site.is_allot_fee_limit_service_fee
     *
     * @mbggenerated
     */
    public void setIsAllotFeeLimitServiceFee(Integer isAllotFeeLimitServiceFee) {
        this.isAllotFeeLimitServiceFee = isAllotFeeLimitServiceFee;
    }
}